### ISSUE TITLE
HMJsonRequest has no initWithUrlString:parameters:callback method

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/cameo#1]
HMJsonRequest has the following methods:

– initWithUrlString:callback:
– initWithUrlString:parameters:

But it doesn't have a initWithUrlString:parameters:callback method, which forces the user to manually encode the GET parameters in the URL string when he wants to use a callback.

**Comment by joamag** [comment]
you now have `(id)initWithUrlString:(NSString *)urlString method:(NSString *)method parameters:(NSArray *)parameters callback:(JsonBlock) callback` does this solve your problem ?

**Comment by tsilva** [comment]
Yes, that should do it.

**Comment by joamag** [comment]
closing it as fixed
