### ISSUE TITLE
Add support for request parameters to support types other than NSString

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/cameo#11]
## Description

Currently the parameters provided to requests only support strings, meaning that I can't send a map like this:

``` objective-c
{
    "number" : @1
}
```
## Solution

A simple way to allow all object datatypes and have them all converted to string is to pass them all through this method:

``` objective-c
NSString *parameter = [NSString stringWithFormat:@"%@", parameter];
```

**Comment by joamag** [comment]
this now considered fixed
