### ISSUE TITLE
Add support for response object parsing

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/cameo#12]
## Description

It would be very helpful to be able to specify which class one wants to have a json response applied to, and have the request methods returns instances of that class instead. For example, if the response was this:

``` json
[
    {
        "name" : "test1",
        "price" : 10
    },
    {
        "name" : "test2",
        "price" : 20
    }
]
```

If I told the method that I wanted that data applied to "Product.class", then I would receive two instances of that class with those values applied to them.

**Comment by joamag** [comment]
@tsilva is this something present in AFNetworking ? If it's where can I have an example of usage...

**Comment by joamag** [comment]
@tsilva this `[object setValuesForKeysWithDictionary:deserializedDictionary]` is the key to solve this problem right ?

**Comment by joamag** [comment]
this is now considered closed, @tsilva take a look at [this file](https://github.com/hivesolutions/cameo/blob/master/src/tests/HMJSONSerializerTest.m) for an example of usage
