### ISSUE TITLE
Callback support for setImageWithURL method

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/cameo#13]
## Description

Need a way to perform actions right after an image is loaded with the setImageWithURL method in the ImageView category (for example: fading in an image right after it's loaded). There's currently no callback support, here is the link to the current category implementation: https://github.com/hivesolutions/cameo/blob/master/src/classes/UIImageView%2BHMImageViewUtil.m

**Comment by joamag** [comment]
@tsilva don't forget triage and priority

**Comment by tsilva** [comment]
ok, will remember to do that from now on
