### ISSUE TITLE
Response object serialization doesn't work when attributes don't exist

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/cameo#14]
## Description

When a key exists in the json map and not in the object, the HMJSONSerializer crashes. Here is a sample error:

'NSUnknownKeyException', reason: '[<Bagger.Category 0x7f9612490130> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key image_url.'

The expected behaviour would be to fail silently and just ignore that attribute (the server may send a lot of values but we may only care about a subset of them).

**Comment by tsilva** [comment]
This is related to #12.

**Comment by joamag** [comment]
this should be fixed overriding the [`setValue:forUndefinedKey`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSKeyValueCoding_Protocol/#//apple_ref/occ/instm/NSObject/setValue:forUndefinedKey:) method instead.

Subclasses can override this method to handle the request in some other way. The default implementation raises an NSUndefinedKeyException.

**Comment by joamag** [comment]
closing this as won't fix
