### ISSUE TITLE
HMProxy seems slow when requesting an image.

### ISSUE THREAD

**Issue by acaldas** [hivesolutions/cameo#16]
## Description

A GET request of a big image with the HMDataSerializer causes a delay on the main thread before invoking the callback.
## Example

``` objective-c
[self.proxy get:url
    parameters:params
    useSession:YES
    serializer:HMDataSerializer.singleton
      callback:^(NSData *response, NSError *error) {
          UIImage *image = [UIImage imageWithData:response];
          callback(image, error);
      }];
```

**Comment by joamag** [comment]
It may be related with this https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSOperationQueue_class/

**Comment by joamag** [comment]
[This article](http://stackoverflow.com/questions/15594882/nsurlconnection-and-multiple-asynchronous-requests-is-it-messing-with-the-data) talks about issues with multiple concurrent HTTP requests, that may be the problem...

**Comment by joamag** [comment]
Closing this as no more information exists about this one.
