### ISSUE TITLE
HMProxyRequest support to follow redirect

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/cameo#18]
## Description

When a request responds with a redirect, the retriever is not following that redirect.

**Comment by joamag** [comment]
There's information on this topic [here](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/RequestChanges.html#//apple_ref/doc/uid/TP40009506-SW1)

**Comment by joamag** [comment]
This should now be working
